#
# Copyright (c) 2023 by Delphix. All rights reserved.
#

"""create all tables

Revision ID: 0156962e865d
Revises:
Create Date: 2023-07-07 14:59:06.761617

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "connector",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user", sa.Text(length=25), nullable=False),
        sa.Column("password", sa.Text(length=25), nullable=False),
        sa.Column("jdbc_url", sa.Text(), nullable=False),
        sa.Column("certificate_key_file", sa.Text(), nullable=True),
        sa.Column("tls_ca_file", sa.Text(), nullable=True),
        sa.Column("ssl", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "data_info",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("data", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "data_set",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("data", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "data_set_job_mapping",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("data", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "load",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("data", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "post_load",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("data", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("post_load")
    op.drop_table("load")
    op.drop_table("data_set_job_mapping")
    op.drop_table("data_set")
    op.drop_table("data_info")
    op.drop_table("connector")
    # ### end Alembic commands ###
